version: '3'
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

  eventstore:
    image: eventstore/eventstore:release-4.0.3
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - default

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - default

  router-service:
    build: ./router-service
    ports:
      - "3000:3000"
    volumes:
      - ./router-service:/home/node/app
    networks:
      - default

  ping-service:
    build: ./ping-service
    volumes:
      - ./ping-service:/home/node/app
    networks:
      - default

networks:
  default:
