version: '3'
services:

  eventstore:
    image: eventstore/eventstore:release-4.0.3
    ports:
      - "2113:2113"
      - "1113:1113"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  nats:
    build:
      context: "./nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"

  router-service:
    build: ./router-service
    ports:
      - "3000:3000"
    volumes:
      - ./router-service:/home/node/app
    depends_on:
      - nats

  ping-service:
    build: ./ping-service
    volumes:
      - ./ping-service:/home/node/app
    depends_on:
      - nats

  users-signup-service:
    build: ./users-signup-service
    volumes:
      - ./users-signup-service:/home/node/app
      - ./rules:/home/node/rules
    depends_on:
      - nats
